name: console
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: mkanenobu <kaneda.1018@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
